icon = {
    'star': '✨',
    'good': '👍',
    'bad': '👎',
    'warning': '⚠️',
    'info': '❗️',
    'question': '❓',
    'ban': '🚫',
    'arrow': '➜',
    'right': '➡️',
    'left': '⬅️',
    'up': '⬆️',
    'down': '⬇️',
    'check': '✅',
    'cross': '❌',
    'running': '🏃',
    'rocket': '🚀',
    'bug': '🐞',
    'fire': '🔥',
    'lock': '🔒',
    'unlock': '🔓',
    'repeat': '🔁',
    'sleep': '💤',
    'lightbulb': '💡',
    'hourglass': '⏳',
    'repeat': '🔁',
}
